import React, { useEffect, useMemo, useState } from 'react';
import { Download, Receipt, RefreshCw } from 'lucide-react';
import { api } from '../api';
import { useAuth } from '../context/AuthContext';

export function BillingSection({ openAuthModal }) {
  const { isAuthenticated } = useAuth();
  const [invoices, setInvoices] = useState([]);
  const [paymentOptions, setPaymentOptions] = useState({ enabled: false, provider: 'none' });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [downloading, setDownloading] = useState('');
  const [paying, setPaying] = useState('');

  useEffect(() => {
    let active = true;
    const requests = isAuthenticated ? [api.paymentOptions(), api.invoices()] : [];
    if (!isAuthenticated) { setLoading(false); setInvoices([]); setError(''); return () => { active = false; }; }
    setLoading(true); setError('');
    Promise.all(requests).then(([options, invoiceList]) => {
      if (active) { setPaymentOptions(options); setInvoices(invoiceList || []); }
    }).catch((err) => { if (active) setError(err.message); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [isAuthenticated]);

  const outstanding = useMemo(() => invoices.filter((invoice) => invoice.status === 'UNPAID')
    .reduce((sum, invoice) => sum + Number(invoice.amount), 0), [invoices]);

  const download = async (invoice) => {
    setDownloading(invoice.id); setError('');
    try {
      const blob = await api.invoicePdf(invoice.id);
      const url = URL.createObjectURL(blob); const link = document.createElement('a');
      link.href = url; link.download = `invoice-${invoice.id}.pdf`; link.click(); URL.revokeObjectURL(url);
    } catch (err) { setError(err.message); }
    finally { setDownloading(''); }
  };

  const pay = async (invoice) => {
    setPaying(invoice.id); setError('');
    try {
      const result = await api.createPayment(invoice.id);
      if (result.checkoutUrl) window.location.assign(result.checkoutUrl);
      else setError('Payment provider did not return a checkout link.');
    } catch (err) { setError(err.message); }
    finally { setPaying(''); }
  };

  return <section className="page-section"><div className="container">
    <div className="page-heading"><span className="eyebrow">Patient accounts</span><h1>Billing & invoices</h1><p>Review charges generated by confirmed appointments, laboratory bookings, and pharmacy orders.</p></div>
    {!isAuthenticated ? <div className="empty-state"><Receipt size={30} /><h2>Sign in to view billing</h2><p>Your invoices are private and visible only to your account.</p><button className="btn btn-primary" onClick={() => openAuthModal('PATIENT')}>Sign in</button></div> : <>
      <div className="billing-summary"><div><span>Total outstanding</span><strong>₹{outstanding.toFixed(2)}</strong></div><span>{paymentOptions.enabled ? `Pay securely with ${paymentOptions.provider}` : 'Online payment provider is not configured'}</span></div>
      {loading && <p className="notice">Loading invoices…</p>}{error && <p className="notice notice-error" role="alert">{error}</p>}
      {!loading && invoices.length === 0 && <div className="empty-state"><Receipt size={30} /><h2>No invoices yet</h2><p>Charges will appear after an appointment, laboratory test, or pharmacy order is confirmed.</p><button className="btn btn-secondary" onClick={() => window.location.reload()}><RefreshCw size={16} /> Refresh</button></div>}
      {!!invoices.length && <div className="invoice-list">{invoices.map((invoice) => <article className="invoice-card" key={invoice.id}><div className="invoice-symbol"><Receipt size={21} /></div><div className="invoice-main"><div className="invoice-topline"><strong>{invoice.description}</strong><span className={`status-pill status-${invoice.status.toLowerCase()}`}>{invoice.status}</span></div><p>{invoice.referenceType.replaceAll('_', ' ')} · {new Date(invoice.createdAt).toLocaleDateString()}</p><small>Invoice {invoice.id}</small></div><strong className="invoice-amount">{invoice.currency} {Number(invoice.amount).toFixed(2)}</strong><div className="invoice-actions"><button className="btn btn-secondary" onClick={() => download(invoice)} disabled={downloading === invoice.id}><Download size={16} /> {downloading === invoice.id ? 'Preparing…' : 'Download'}</button>{invoice.status === 'UNPAID' && <button className="btn btn-primary" onClick={() => pay(invoice)} disabled={!paymentOptions.enabled || paying === invoice.id}>{paying === invoice.id ? 'Opening…' : 'Pay invoice'}</button>}</div></article>)}</div>}
      {!paymentOptions.enabled && !!invoices.length && <p className="notice notice-muted">Invoice viewing and PDF downloads are ready. Choose and configure a payment provider to enable online payments.</p>}
    </>}
  </div></section>;
}
